### ISSUE TITLE
actions: smoother playstore publishing

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/myplanet#3706]
```
      - name: publish AAB to playstore
        id: playstore
        if: github.ref == 'refs/heads/master' && matrix.build == 'lite'
        continue-on-error: true
        uses: dogi/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.ole.planet.myplanet
          releaseFiles: output/myPlanet.aab
          track: internal
          releaseName: "${{ env.ANDROID_VERSION_CODE }} (${{ env.ANDROID_VERSION_NAME }})"
          status: completed

      - name: publish AAB to playstore fallback
        if: github.ref == 'refs/heads/master' && matrix.build == 'lite' && steps.playstore.outcome == 'failure'
        uses: dogi/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.ole.planet.myplanet
          releaseFiles: output/myPlanet.aab
          track: internal
          releaseName: "${{ env.ANDROID_VERSION_CODE }} (${{ env.ANDROID_VERSION_NAME }})"
          status: completed
          changesNotSentForReview: true
```
